When dividing by zero, the program returned zero and did not throw an exception. This wasn't caught initially as I did not have a test case that tested for dividing by zero. To fix the issue I added a check in my operate method to see if the denominator is equal to zero, and if it is true it throws an FormulaEvaluationException. This should now pass tests that check for dividing by zero.
